"
" MAIN CUSTOMIZATION FILE
"

set path=~/
" Enable loading filetype and indentation plugins
filetype plugin on
filetype indent on

" Turn syntax highlighting on
syntax on

"
" GLOBAL SETTINGS
"

" Write contents of the file, if it has been modified, on buffer exit
set autowrite

" Allow backspacing over everything
"set backspace=indent,eol,start
"退格键能用
set backspace=indent,eol,start
" Insert mode completion options
set completeopt=menu,longest,preview

" Use UTF-8 as the default buffer encoding
set enc=utf-8
"编码设置
"set enc=gb2312
"set fenc=gb2312
set tenc=gb2312
"set enc=utf-8
"set fenc=utf-8
"set tenc=utf-8

" Remember up to 100 'colon' commmands and search patterns
set history=100

" Enable incremental search
set incsearch

" Always show status line, even for one window
set laststatus=2

" Jump to matching bracket for 2/10th of a second (works with showmatch)
set matchtime=2

" Don't highlight results of a search
"set nohlsearch
set hlsearch

" Enable CTRL-A/CTRL-X to work on octal and hex numbers, as well as characters
set nrformats=octal,hex,alpha

" Use F10 to toggle 'paste' mode
"set pastetoggle=<F10>

" Show line, column number, and relative position within a file in the status line
set ruler

" Scroll when cursor gets within 3 characters of top/bottom edge
set scrolloff=3

" Round indent to multiple of 'shiftwidth' for > and < commands
set shiftround

" Use 4 spaces for (auto)indent
set shiftwidth=4

" Show (partial) commands (or size of selection in Visual mode) in the status line
set showcmd

" When a bracket is inserted, briefly jump to a matching one
set showmatch

" Don't request terminal version string (for xterm)
set t_RV=

" Use 4 spaces for <Tab> and :retab
set tabstop=4

" Write swap file to disk after every 50 characters
set updatecount=50

" Remember things between sessions
"
" '20  - remember marks for 20 previous files
" \"50 - save 50 lines for each register
" :20  - remember 20 items in command-line history 
" %    - remember the buffer list (if vim started without a file arg)
" n    - set name of viminfo file
set viminfo='20,\"50,:20,%,n~/.viminfo

" Use menu to show command-line completion (in 'full' case)
set wildmenu

" Set command-line completion mode:
"   - on first <Tab>, when more than one match, list all matches and complete
"     the longest common  string
"   - on second <Tab>, complete the next full match and show menu
set wildmode=list:longest,full

" Go back to the position the cursor was on the last time this file was edited
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")|execute("normal `\"")|endif

" Fix my <Backspace> key (in Mac OS X Terminal)
set t_kb=
fixdel

" Avoid loading MatchParen plugin
let loaded_matchparen = 1

" netRW: Open files in a split window
let g:netrw_browse_split = 1

"
" MAPPINGS
"

" save changes
map ,s :w<CR>
" exit vim without saving any changes
map ,q :q!<CR>
" exit vim saving changes
map ,w :x<CR>
" switch to upper/lower window quickly
map <C-J> <C-W>j
map <C-K> <C-W>k
" use CTRL-F for omni completion
imap <C-F> 
" map CTRL-L to piece-wise copying of the line above the current one
imap <C-L> @@@<ESC>hhkywjl?@@@<CR>P/@@@<CR>3s
" map ,f to display all lines with keyword under cursor and ask which one to
" jump to
nmap ,f [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
" use <F6> to toggle line numbers
nmap <silent> <F6> :set number!<CR>
" page down with <Space>
nmap <Space> <PageDown>
" open filename under cursor in a new window (use current file's working
" directory) 
nmap gf :new %:p:h/<cfile><CR>
" map <Alt-p> and <Alt-P> to paste below/above and reformat
nnoremap <Esc>P  P'[v']=
nnoremap <Esc>p  p'[v']=
" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv 

" Generic highlight changes
"highlight Comment cterm=none ctermfg=Gray
"highlight IncSearch cterm=none ctermfg=Black ctermbg=DarkYellow
"highlight Search cterm=none ctermfg=Black ctermbg=DarkYellow
"highlight String cterm=none ctermfg=DarkGreen
"highlight treeDir cterm=none ctermfg=Cyan
"highlight treeUp cterm=none ctermfg=DarkYellow
"highlight treeCWD cterm=none ctermfg=DarkYellow
"highlight netrwDir cterm=none ctermfg=Cyan

" my custome
" ######################################################
" Set the <Leader> for combo commands
let mapleader = ","


" jj replace esc
inoremap jj <ESC>



"ctags
nmap <silent> <F3> :tselect<CR>

"语法检查
"nmap <silent> <F9> :! d:\wamp\bin\php\php5.4.12\php.exe -l  % <CR>
nmap <silent> <F9> :! C:\wamp\bin\php\php5.4.12\php.exe -l  % &<CR>
"nmap <silent> <F10> :! find . -name %  -exec /home/zhouping01/workspace/tools/checkstyle.sh {} \;<CR>
nmap <silent> <F10> :! d:\cygwin64\bin\bash.exe /home/zhouping01/workspace/tools/checkstyle.sh % <CR>
nmap <silent> <F11> :! d:\cygwin64\bin\bash.exe /home/zhouping01/workspace/tools/checkstyle.start.sh % <CR>
"nmap <silent> <F12> :! d:\cygwin64\bin\bash.exe cd .. && d:\cygwin64\home\zhouping01\workspace\tools\checkprobuf.sh %<CR>
"nmap <silent> <F12> :! d:\cygwin64\bin\bash.exe /home/zhouping01/workspace/tools/checkprobuf.sh %<CR>
nmap <silent> <F12> :! svn ci % -m "optimize" <CR>
"nmap <silent> <F11> :lcd %:p:h<Bar>! D:\cygwin64\bin\bash.exe D:\cygwin64\home\zhouping01\workspace/tools/cp_to_dev.sh  % & <CR>

"设置注释的颜色
hi Comment ctermfg=6

map tp :tabp<cr>
map tn :tabn<cr>

nmap <silent> <F5> :r! date +"\%F \%T"<CR>

set tags=tags;
set autochdir 
colorscheme evening

" 不同时显示多个文件的 tag ，只显示当前文件的
let Tlist_Show_One_File=1 

" 如果 taglist 窗口是最后一个窗口，则退出 vim
let Tlist_Exit_OnlyWindow=1

"让当前不被编辑的文件的方法列表自动折叠起来
let Tlist_File_Fold_Auto_Close=1

" 这项必须设定，否则出错,配置taglist的ctags路径
let Tlist_Ctags_Cmd = 'ctags'

"设置界面分割
"let g:winManagerWindowLayout = "BufExplorer,FileExplorer|TagList"
let g:winManagerWindowLayout='FileExplorer|TagList' 
"文件，函数列表
nmap <silent> <F7> :WMToggle<cr> 
"nmap wm :WMToggle<cr> 

"函数列表
nmap <silent> <F8> :TlistToggle<cr> 

let g:miniBufExplMapCTabSwitchBufs=1 
let g:miniBufExplMapWindowsNavVim=1 
let g:miniBufExplMapWindowNavArrows=1 

set path=~/
" ######################################################
